version: "3.8"
services:
  pendroid:
    image: servalcyber/pendroid
    container_name: pendroid
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
      - "8000:8000"
      - "7777:7777"
      - "5000:5000"
    volumes:
      - ./apk:/root/apk
    working_dir: /root
