version: '3'

services:
  app:
    build:
      dockerfile: BUILD/Dockerfile
      args:
        password: "beef-xss"
    image: beef-xss
    container_name: beef-xss
    restart: always
    ports:
      - "3000:3000"
