version: '3'

services:
  ldap:
    build: 
      dockerfile: BUILD/Dockerfile
      args:
        SAMBA_VERSION: "4.15.5"
    image: ldap
    container_name: ldap
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      SAMBA_DC_REALM: cobblepot59.int
      SAMBA_DC_DOMAIN: cobblepot59
      SAMBA_DC_ADMIN_PASSWD: Password1
      SAMBA_DC_DNS_BACKEND: SAMBA_INTERNAL
